#Parte 3 - docker compose

version: '3'

services:
  webproxy:
    image: abrantedevops/projeto:latest
    restart: unless-stopped
    networks:
      - wordpress
    ports:
      - 8080:8080
    depends_on:
      - webserver

  database:
    image: mysql:5.7
    volumes:
      - my:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress

  webserver:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - 80:80
    volumes:
      - app:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress


volumes:
  app:
  my:

networks:
  wordpress:
    driver: bridge